### ISSUE TITLE
Issue with verify mode and 2.0.0

### ISSUE THREAD

**Issue by bhollis** [seek-oss/css-modules-typescript-loader#10]
Hi there, I just tried updating to 2.0.0, and when running with the "verify" option in my CI, I get this: https://travis-ci.org/DestinyItemManager/DIM/builds/518150743?utm_source=github_status&utm_medium=notification

**Comment by mattsjones** [comment]
Hey mate. Had a quick look. The error is coming from your typescript loader not our loader. No idea what the cause. Need more info to debug and confirm the issue.

**Comment by bhollis** [comment]
Thanks! I’m thinking that’s a red herring since Webpack chains loaders. This happens when I change nothing but the css module version, and only when verify mode is on.

**Comment by mattsjones** [comment]
@bhollis Yeah, I understand, just not enough info to go on by itself. If you can reproduce the issue in a sample repo then I can definitely take a look. I'm not super familiar with the `awesome-typescript-loader` as we use babel for TS compilation. 

Btw great work with DIM. Big fan!

**Comment by bhollis** [comment]
Thanks! I’ll see if I can put together a more minimal repro on the weekend.
