### ISSUE TITLE
Error: No exported locals found

### ISSUE THREAD

**Issue by kilgarenone** [seek-oss/css-modules-typescript-loader#15]
I have a `index.scss` file with such CSS rules:

```
@font-face {
   font-family: Lato;
   src: url('font-lato/lato-bold-webfont.woff2') format('woff2')
   font-weight: 700;
}

body {
  font-family: Lato;
}
```
And I got this error `Error: No exported locals found for C:\Users\kw\pm\src\css\index.scss
    at Object.module.exports (C:\Users\kw\pm\node_modules\css-modules-typescript-loader\index.js:73:19)`

It works fine if the rules are just class selector `.selector { color: red }`.

**Comment by kraenhansen** [comment]
I've proposed a fix (with a passing test) for this https://github.com/seek-oss/css-modules-typescript-loader/pull/16
