### ISSUE TITLE
Place css-modules-typescript-loader directly after css-loader in your webpack config

### ISSUE THREAD

**Issue by alexeychikk** [seek-oss/css-modules-typescript-loader#18]
Readme is unclear. It says
> Place css-modules-typescript-loader directly after css-loader in your webpack config.

But the code example below shows `css-modules-typescript-loader` being placed **BEFORE** `css-loader`. Where should I place it?

**Comment by tobyhinloopen** [comment]
IIRC webpack "use" statements are executed from bottom to top; for something to execute "after" something, it must be placed before it in the "use" list.
