### ISSUE TITLE
Mode 'verify' and tests do not run on Windows

### ISSUE THREAD

**Issue by alexanderogilvie** [seek-oss/css-modules-typescript-loader#19]
Under Windows (just imagine you WOULD or WOULD HAVE TO use it ;) ) the tests fail.
As well 'verify' mode does not work properly, at least if you work with the git config flag core.autocrlf=true. The problem is, that by checking out a branch or changes to CSS module type declaration files, the line endings are set from LF (what is in the repo) to CRLF. The result is, that the comparison in 'verify' between the file on disk and the generated module definition finds diffs and fails by that.

**Comment by alexanderogilvie** [comment]
I'm going to open a pull request with a proposal, where I make the compare "line-separator-safe" by always convert occuring CRLFs to LFs. 

An alternative would be to use a system-specific line separator using `import { EOL } from 'os';`, but that would lead to different generated line endings on different systems, which I wouldn't prefer. In addition, if git's core.autocrlf is set to false on a Windows machine, the problem would still occur (the files would keep the LF line endings after checkout, but the generated code would have CRLF).

**Comment by alexanderogilvie** [comment]
In addition, if type declaration files are checked out under Windows with core.autocrlf=true and then mode 'emit' is started, it will overwrite the files with CRLF (the auto-converted file version) by LF, which leads to a git diff only because of line separators. Which ist not nice.

**Comment by pstrh** [comment]
Same issue here. Would be great if verify mode would properly work on Windows.
